using System;
using System.Collections.Generic;

// Token: 0x02000048 RID: 72
public static class StatLabels
{
	// Token: 0x040001EC RID: 492
	public static readonly Dictionary<StatType, string> Labels = new Dictionary<StatType, string>
	{
		{
			StatType.FireRate,
			"fire_rate_label"
		},
		{
			StatType.ReloadRate,
			"reload_rate_label"
		},
		{
			StatType.MaxAmmo,
			"max_ammo_label"
		},
		{
			StatType.BulletDamage,
			"bullet_damage_label"
		},
		{
			StatType.SummonDamage,
			"summon_damage_label"
		},
		{
			StatType.SummonAttackSpeed,
			"summon_attack_speed_label"
		},
		{
			StatType.Projectiles,
			"projectiles_label"
		},
		{
			StatType.ProjectileSpeed,
			"projectile_speed_label"
		},
		{
			StatType.ProjectileSize,
			"projectile_size_label"
		},
		{
			StatType.Knockback,
			"knockback_label"
		},
		{
			StatType.MoveSpeed,
			"move_speed_label"
		},
		{
			StatType.WalkSpeed,
			"walk_speed_label"
		},
		{
			StatType.Spread,
			"spread_label"
		},
		{
			StatType.Bounce,
			"bounce_label"
		},
		{
			StatType.Piercing,
			"piercing_label"
		},
		{
			StatType.MaxHP,
			"max_hp_label"
		},
		{
			StatType.CharacterSize,
			"character_size_label"
		},
		{
			StatType.PickupRange,
			"pickup_range_label"
		},
		{
			StatType.VisionRange,
			"vision_range_label"
		},
		{
			StatType.Dodge,
			"dodge_label"
		},
		{
			StatType.DodgeCapMod,
			"dodge_cap_label"
		}
	};
}
